/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int DO = 7;
  /** RegularExpression Id. */
  int WHILE = 8;
  /** RegularExpression Id. */
  int ADD = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int NOASSIGN = 11;
  /** RegularExpression Id. */
  int NULL = 12;
  /** RegularExpression Id. */
  int ONE = 13;
  /** RegularExpression Id. */
  int SEMI = 14;
  /** RegularExpression Id. */
  int LBRK = 15;
  /** RegularExpression Id. */
  int RBRK = 16;
  /** RegularExpression Id. */
  int IN = 17;
  /** RegularExpression Id. */
  int OUT = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int IDENT = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"begin\"",
    "\"end\"",
    "\"do\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"!=\"",
    "\"0\"",
    "\"1\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"in\"",
    "\"out\"",
    "\",\"",
    "<IDENT>",
  };

}
